package prime

import (
	"arit/modules"
	"errors"
)

// Should eventually be generated by go generate command using function comments
func Help() string {
	return "topic \"help prime\" NYI"
}

func Eval(args []string) (any, error) {

	switch args[0] {
	case "is":
		v, err := modules.SingleInt64(args[1:])
		if err != nil {
			return v, err
		}
		return isprime(v)
	default:
		return nil, errors.New("arg: " + args[0] + " is not supported")
	}
}
