package random

import (
	"arit/modules"
	"errors"
)

// Should eventually be generated by go generate command using function comments

func Help() string {
	return "topic \"help rand\" NYI"
}

func Eval(args []string) (any, error) {

	switch args[0] {
	case "cap", "Capitilization":
		v, err := single(args[1:])
		if err != nil {
			return v, err
		}
		return capitilization(trim(v))
	case "num", "number":
		return number(), nil
	case "gen64", "generate64":
		n, a, b, err := (modules.TripleInt64(args[1:]))
		if err != nil {
			return nil, err
		}
		return generate64(n, a, b)
	case "inopen", "open":
		a, b, err := modules.DoubleInt64(args[1:])
		if err != nil {
			return nil, err
		}
		return inOpen(a, b)
	case "in", "inclosed", "closed":
		a, b, err := modules.DoubleInt64(args[1:])
		if err != nil {
			return nil, err
		}
		return inOpen(a, b)
	case "d6":
		return d6()
	case "d4":
		return inClosed(1, 4)
	case "d3":
		return d3()
	default:
		return nil, errors.New("arg: " + args[0] + " is not supported")
	}
}
